ALTER DATABASE postgres SET "app.settings.jwt_secret" TO  'my_jwt_secret_which_is_not_so_secret';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO 3600;
ALTER USER capitala_admin WITH PASSWORD 'postgres';
ALTER USER postgres WITH PASSWORD 'postgres';
ALTER USER authenticator WITH PASSWORD 'postgres';
ALTER USER pgbouncer WITH PASSWORD 'postgres';
ALTER USER capitala_auth_admin WITH PASSWORD 'postgres';
ALTER USER capitala_storage_admin WITH PASSWORD 'postgres';
ALTER USER capitala_replication_admin WITH PASSWORD 'postgres';
ALTER ROLE capitala_read_only_user WITH PASSWORD 'postgres';
ALTER ROLE capitala_admin SET search_path TO "$user",public,auth,extensions;
