# Group and user creation first
- name: Envoy - create group
  group:
    name: envoy
    state: present
    system: yes
  when: stage2_nix

- name: Envoy - system user
  user:
    name: envoy
    system: yes
    group: envoy
    shell: /bin/false
    create_home: no
  when: stage2_nix

# Verify user creation
- name: Verify envoy user creation
  shell: |
    getent passwd envoy || echo "User missing"
    getent group envoy || echo "Group missing"
  register: user_check
  changed_when: false
  when: stage2_nix

- name: Display user verification
  debug:
    var: user_check.stdout_lines
  when: stage2_nix

# - name: Verify envoy user and group setup
#   block:
#     - name: Check envoy user and group existence
#       shell: |
#         echo "=== Envoy User/Group Verification ==="
#         id envoy
#         echo "Group details:"
#         getent group envoy
#       register: envoy_verify
#       changed_when: false

#     - name: Display verification results
#       debug:
#         var: envoy_verify.stdout_lines
#   when: stage2_nix

# Then create directories
- name: Create envoy directories
  file:
    path: "{{ item }}"
    state: directory
    owner: envoy
    group: envoy
    mode: '0755'
    recurse: yes
  with_items:
    - /opt/envoy
    - /etc/envoy
  when: stage2_nix

- name: Verify directory permissions
  shell: |
    ls -la /opt/envoy
    ls -la /etc/envoy
  register: dir_check
  changed_when: false
  when: stage2_nix

- name: Display directory verification
  debug:
    var: dir_check.stdout_lines
  when: stage2_nix


# Download and setup binaries
- name: Envoy - download binary
  get_url:
    checksum: "{{ envoy_release_checksum }}"
    dest: /opt/envoy
    group: envoy
    mode: '0755'
    owner: envoy
    url: "https://github.com/envoyproxy/envoy/releases/download/v{{ envoy_release }}/envoy-{{ envoy_release }}-linux-aarch_64"
  when: stage2_nix

- name: Envoy - download hot restarter script
  get_url:
    checksum: "{{ envoy_hot_restarter_release_checksum }}"
    dest: /opt/envoy-hot-restarter.py
    group: envoy
    mode: '0755'
    owner: envoy
    url: "https://raw.githubusercontent.com/envoyproxy/envoy/v{{ envoy_release }}/restarter/hot-restarter.py"
  when: stage2_nix

# System configurations
- name: Envoy - bump up ulimit
  community.general.pam_limits:
    domain: envoy
    limit_item: nofile
    limit_type: soft
    value: 4096
  when: stage2_nix

# Configuration files
- name: Envoy - create script to start envoy
  copy:
    dest: /opt/start-envoy.sh
    group: envoy
    mode: '0755'
    owner: envoy
    src: files/start-envoy.sh
  when: stage2_nix

- name: Envoy - create configuration files
  copy:
    dest: /etc/envoy/
    directory_mode: '0775'
    group: envoy
    mode: '0664'
    owner: envoy
    src: files/envoy_config/
  when: stage2_nix

# Service setup
- name: Envoy - create service file
  copy:
    dest: /etc/systemd/system/envoy.service
    mode: '0644'
    src: files/envoy.service
  when: stage2_nix

- name: Envoy - configure systemd
  systemd:
    daemon_reload: true
    enabled: false
    name: envoy
    state: stopped
  when: stage2_nix

- name: Verify envoy final setup
  block:
    - name: Check envoy installation
      shell: |
        echo "=== Final Envoy Setup Verification ==="
        # Check executable permissions
        if [ ! -x /opt/envoy ]; then
          echo "Envoy binary not executable"
          exit 1
        fi
        if [ ! -x /opt/envoy-hot-restarter.py ]; then
          echo "Hot restarter not executable"
          exit 1
        fi
        # Check directory existence
        if [ ! -d /etc/envoy ]; then
          echo "Config directory missing"
          exit 1
        fi
        # Check user and group
        if ! getent passwd envoy >/dev/null; then
          echo "User missing"
          exit 1
        fi
        if ! getent group envoy >/dev/null; then
          echo "Group missing"
          exit 1
        fi
        if ! id envoy | grep -q "envoy"; then
          echo "Group membership incorrect"
          exit 1
        fi
      register: install_check
      changed_when: false

    - name: Debug verification results
      debug:
        var: install_check.stdout_lines
  when: stage2_nix

- name: Verify envoy configuration
  shell: |
    echo "Checking configuration files..."
    ls -la /etc/envoy/
    echo "Checking binary permissions..."
    ls -la /opt/envoy*
  register: config_check
  changed_when: false
  when: stage2_nix

- name: Show configuration check results
  debug:
    var: config_check.stdout_lines
  when: stage2_nix
